name: js_promise
description: A package providing interop functionality with JavaScript Promises.
version: 0.1.0
homepage: https://github.com/hacker1024/js_promise.dart

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  js: ^0.6.4

dev_dependencies:
  lint: ^1.10.0
